name: GCP Auth test
description: Test GitHub Actions authentication with GCP

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  auth-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCP_SERVICE_ACCOUNT }}"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2


      - name: verify identity
        run: gcloud auth list

      - name: list bucket
        run: gcloud storage buckets list